// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjjsKUmAty2r6xgQurO2uDgC1RDdikVXg',
    appId: '1:202278560441:web:1f32c23311d88dbc8cf168',
    messagingSenderId: '202278560441',
    projectId: 'ele-192',
    authDomain: 'ele-192.firebaseapp.com',
    storageBucket: 'ele-192.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhGzM20icHI_mWhvjVkE4ehp4pOrEAPn4',
    appId: '1:202278560441:android:1122faae0bf6f2a18cf168',
    messagingSenderId: '202278560441',
    projectId: 'ele-192',
    storageBucket: 'ele-192.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZqgyK-p9hwXnzbxFN8OZNNtjJOJNmPTU',
    appId: '1:202278560441:ios:9022015677544f8e8cf168',
    messagingSenderId: '202278560441',
    projectId: 'ele-192',
    storageBucket: 'ele-192.firebasestorage.app',
    iosBundleId: 'com.example.final66106337',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZqgyK-p9hwXnzbxFN8OZNNtjJOJNmPTU',
    appId: '1:202278560441:ios:9022015677544f8e8cf168',
    messagingSenderId: '202278560441',
    projectId: 'ele-192',
    storageBucket: 'ele-192.firebasestorage.app',
    iosBundleId: 'com.example.final66106337',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjjsKUmAty2r6xgQurO2uDgC1RDdikVXg',
    appId: '1:202278560441:web:252ab6495aa3e8978cf168',
    messagingSenderId: '202278560441',
    projectId: 'ele-192',
    authDomain: 'ele-192.firebaseapp.com',
    storageBucket: 'ele-192.firebasestorage.app',
  );
}
